wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/wr.png -O wR.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/wk.png -O wK.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/wq.png -O wQ.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/wp.png -O wP.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/wn.png -O wN.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/wb.png -O wB.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/br.png -O bR.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/bk.png -O bK.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/bq.png -O bQ.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/bp.png -O bP.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/bn.png -O bN.png
wget https://images.chesscomfiles.com/chess-themes/pieces/$1/300/bb.png -O bB.png